services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - app-network

  mongo:
    image: mongo:6
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
