services:
  app:
    container_name: my-app-dev
    build:
      context: ../
      dockerfile: docker/Dockerfile.dev
    ports:
      - "5000:5000"
    env_file:
      - ../.env.development
    volumes:
      - ../:/app
      - /app/node_modules
    depends_on:
      - mongo
      - rabbitmq
    command: npm run dev

  mongo:
    container_name: mongo-dev

  rabbitmq:
    container_name: rabbitmq-dev
